### ISSUE TITLE
Please upload reflex-dom-svg to hackage

### ISSUE THREAD

**Issue by hamishmack** [qfpl/reflex-dom-svg#4]
We are using reflex-dom-svg [here](https://github.com/leksah/leksah/blob/master/src/IDE/Web/Widget/Tree.hs#L43) to draw little triangles for the workspace tree view in Leksah's new web UI.  Please can you upload reflex-dom-svg to hackage as it would be nice not to have to pull reflex-dom-svg in from source?

**Comment by mankyKitty** [comment]
omg, _users_.

The reason I haven't uploaded this to hackage yet is because the version of reflex-dom this package depends on wasn't on hackage. That was a while ago so I'll see what I can do to make this happen.

**edit**: also how is the package? thoughts/issues/suggestions/requests?

**Comment by mankyKitty** [comment]
trying to sort out some travis integration but this shouldn't be too far off. Sorry for the delay.

**Comment by mankyKitty** [comment]
https://hackage.haskell.org/package/reflex-dom-svg-0.3.2.0 :tada: 

There are a few bug fixes and updates in the version uploaded to hackage, hence the new version. Let us know if there are any issues.
